// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.Persistence;

#nullable disable

namespace Sistema.Persistence.Migrations
{
    [DbContext(typeof(SistemaDBContext))]
    [Migration("20241127032136_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Sistema.Domain.Calificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alumno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntaje")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("calificaciones", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cursos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc4bf0fa-b30c-462e-8fd4-927c5fbee307"),
                            Descripcion = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            FechaPublicacion = new DateTime(2024, 11, 27, 3, 21, 35, 278, DateTimeKind.Utc).AddTicks(358),
                            Titulo = "Ergonomic Cotton Fish"
                        },
                        new
                        {
                            Id = new Guid("4f379161-ef65-44e7-b224-ccf2f54e44c6"),
                            Descripcion = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            FechaPublicacion = new DateTime(2024, 11, 27, 3, 21, 35, 278, DateTimeKind.Utc).AddTicks(1443),
                            Titulo = "Awesome Wooden Chicken"
                        },
                        new
                        {
                            Id = new Guid("aa50a82c-1f9e-4a6f-9ce7-cec97dca668e"),
                            Descripcion = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            FechaPublicacion = new DateTime(2024, 11, 27, 3, 21, 35, 278, DateTimeKind.Utc).AddTicks(1556),
                            Titulo = "Intelligent Fresh Ball"
                        },
                        new
                        {
                            Id = new Guid("21e79cb8-451b-4857-b7f3-936c8002d4ca"),
                            Descripcion = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            FechaPublicacion = new DateTime(2024, 11, 27, 3, 21, 35, 278, DateTimeKind.Utc).AddTicks(1586),
                            Titulo = "Small Fresh Pizza"
                        },
                        new
                        {
                            Id = new Guid("cf12e676-3512-46c1-90e0-795c3c987199"),
                            Descripcion = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            FechaPublicacion = new DateTime(2024, 11, 27, 3, 21, 35, 278, DateTimeKind.Utc).AddTicks(1611),
                            Titulo = "Ergonomic Cotton Pizza"
                        },
                        new
                        {
                            Id = new Guid("1b0cead1-a0f6-4a1b-bb0b-3d11e641c489"),
                            Descripcion = "The Football Is Good For Training And Recreational Purposes",
                            FechaPublicacion = new DateTime(2024, 11, 27, 3, 21, 35, 278, DateTimeKind.Utc).AddTicks(1652),
                            Titulo = "Incredible Fresh Bacon"
                        },
                        new
                        {
                            Id = new Guid("b014f01b-4efd-4f5f-ba3c-a0825c189d47"),
                            Descripcion = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            FechaPublicacion = new DateTime(2024, 11, 27, 3, 21, 35, 278, DateTimeKind.Utc).AddTicks(1714),
                            Titulo = "Rustic Steel Table"
                        },
                        new
                        {
                            Id = new Guid("9d711dec-3442-4855-a3cb-492d523e9796"),
                            Descripcion = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            FechaPublicacion = new DateTime(2024, 11, 27, 3, 21, 35, 278, DateTimeKind.Utc).AddTicks(1743),
                            Titulo = "Handcrafted Plastic Bike"
                        },
                        new
                        {
                            Id = new Guid("1d825d61-a5b2-4fe7-9173-a379e11c732b"),
                            Descripcion = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            FechaPublicacion = new DateTime(2024, 11, 27, 3, 21, 35, 278, DateTimeKind.Utc).AddTicks(1771),
                            Titulo = "Handcrafted Metal Towels"
                        });
                });

            modelBuilder.Entity("Sistema.Domain.CursoInstructor", b =>
                {
                    b.Property<Guid>("InstructorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.HasKey("InstructorId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("cursos_instructores", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.CursoPrecio", b =>
                {
                    b.Property<Guid>("PrecioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.HasKey("PrecioId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("cursos_precios", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("instructores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d86db4d-8ae2-4609-a453-442bac91d966"),
                            Apellidos = "Schoen",
                            Grado = "Dynamic Directives Planner",
                            Nombre = "Corrine"
                        },
                        new
                        {
                            Id = new Guid("a2b37818-c8d8-401f-b43c-b52ac5fd6b74"),
                            Apellidos = "Konopelski",
                            Grado = "Regional Security Strategist",
                            Nombre = "Keeley"
                        },
                        new
                        {
                            Id = new Guid("8ced7dc0-52de-4ca5-a871-304f51f68c07"),
                            Apellidos = "Macejkovic",
                            Grado = "Direct Configuration Supervisor",
                            Nombre = "Ambrose"
                        },
                        new
                        {
                            Id = new Guid("b47100d6-7f22-486b-9346-0d14f05b9cba"),
                            Apellidos = "Daugherty",
                            Grado = "Lead Solutions Director",
                            Nombre = "Milo"
                        },
                        new
                        {
                            Id = new Guid("0ee0cd53-66fe-424d-8811-6bf9144dfa26"),
                            Apellidos = "VonRueden",
                            Grado = "National Quality Specialist",
                            Nombre = "Schuyler"
                        },
                        new
                        {
                            Id = new Guid("f94f7107-3079-4c15-ada8-95dfe37670d1"),
                            Apellidos = "Swift",
                            Grado = "Product Usability Consultant",
                            Nombre = "Angie"
                        },
                        new
                        {
                            Id = new Guid("509e6d3e-b0ec-4990-81b7-2379bee4b92e"),
                            Apellidos = "Towne",
                            Grado = "Dynamic Accounts Agent",
                            Nombre = "Stewart"
                        },
                        new
                        {
                            Id = new Guid("648de723-7649-4fd2-b485-03b7b820aea7"),
                            Apellidos = "Maggio",
                            Grado = "Central Intranet Administrator",
                            Nombre = "Janet"
                        },
                        new
                        {
                            Id = new Guid("5af6fb50-d1a2-468a-a9ba-244d7d7a75fe"),
                            Apellidos = "O'Keefe",
                            Grado = "District Accounts Supervisor",
                            Nombre = "Walter"
                        },
                        new
                        {
                            Id = new Guid("d264d29d-0184-44b4-b502-592ca415c0f7"),
                            Apellidos = "Lueilwitz",
                            Grado = "Regional Solutions Administrator",
                            Nombre = "Jude"
                        });
                });

            modelBuilder.Entity("Sistema.Domain.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("imagenes", (string)null);
                });

            modelBuilder.Entity("Sistema.Domain.Precio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("PrecioActual")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioPromocion")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("precios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e7faabc-1d37-4ee8-a00a-8a4b083cfe5c"),
                            Nombre = "Precio standard",
                            PrecioActual = 10.0m,
                            PrecioPromocion = 8.0m
                        });
                });

            modelBuilder.Entity("Sistema.Domain.Calificacion", b =>
                {
                    b.HasOne("Sistema.Domain.Curso", "Curso")
                        .WithMany("Calificaciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Sistema.Domain.CursoInstructor", b =>
                {
                    b.HasOne("Sistema.Domain.Curso", "Curso")
                        .WithMany("CursoInstructores")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Domain.Instructor", "Instructor")
                        .WithMany("CursoInstructores")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Sistema.Domain.CursoPrecio", b =>
                {
                    b.HasOne("Sistema.Domain.Curso", "Curso")
                        .WithMany("CursoPrecios")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Domain.Precio", "Precio")
                        .WithMany("CursoPrecios")
                        .HasForeignKey("PrecioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Precio");
                });

            modelBuilder.Entity("Sistema.Domain.Photo", b =>
                {
                    b.HasOne("Sistema.Domain.Curso", "Curso")
                        .WithMany("Photos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Sistema.Domain.Curso", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("CursoInstructores");

                    b.Navigation("CursoPrecios");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Sistema.Domain.Instructor", b =>
                {
                    b.Navigation("CursoInstructores");
                });

            modelBuilder.Entity("Sistema.Domain.Precio", b =>
                {
                    b.Navigation("CursoPrecios");
                });
#pragma warning restore 612, 618
        }
    }
}
